# Generated by Django 5.1.5 on 2025-02-03 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_barang', models.CharField(max_length=100)),
                ('berat', models.FloatField()),
                ('ukuran', models.FloatField()),
                ('agen_pengiriman', models.CharField(max_length=100)),
                ('tujuan_pengiriman', models.CharField(max_length=100)),
                ('nama_pengirim', models.CharField(max_length=100)),
                ('nama_penerima', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
