# Generated by Django 5.1.5 on 2025-02-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='jenis_barang',
            new_name='jenis_cargo',
        ),
    ]
